name: Azure Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      
      - name: Terraform Plan
        run: terraform plan
        env:
          TF_VAR_client_secret: ${{ secrets.CLIENT_SECRET }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_client_secret: ${{ secrets.CLIENT_SECRET }}
      # trigger change